from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .config import load_config
from .eval import run_eval
from .jsonl import read_jsonl
from .paths import preferences_path, regrets_path, report_path, sft_path
from .schema import validate_preference, validate_regret, validate_sft


def export_project(project_dir: Path) -> dict[str, Path]:
    config = load_config(project_dir)
    eval_result = run_eval(project_dir, dry_run=True)
    regrets = read_jsonl(regrets_path(project_dir), validate_regret)
    preferences = read_jsonl(preferences_path(project_dir), validate_preference)
    sft_examples = read_jsonl(sft_path(project_dir), validate_sft)

    exports_dir = project_dir / "exports"
    exports_dir.mkdir(parents=True, exist_ok=True)

    dataset_card = exports_dir / "DATASET_CARD.md"
    model_card = exports_dir / "MODEL_CARD.md"
    report = report_path(project_dir)
    report.parent.mkdir(parents=True, exist_ok=True)

    dataset_card.write_text(
        render_dataset_card(project_dir, regrets, preferences, sft_examples),
        encoding="utf-8",
    )
    model_card.write_text(render_model_card(config, eval_result), encoding="utf-8")
    report.write_text(
        render_report(config, eval_result, dataset_card=dataset_card, model_card=model_card),
        encoding="utf-8",
    )
    return {
        "dataset_card": dataset_card,
        "model_card": model_card,
        "report": report,
    }


def render_dataset_card(
    project_dir: Path,
    regrets: list[dict[str, Any]],
    preferences: list[dict[str, Any]],
    sft_examples: list[dict[str, Any]],
) -> str:
    return f"""# PostTrain Garden Dataset Card

Project: `{project_dir}`

## Composition

- Regrets: {len(regrets)}
- Preference pairs: {len(preferences)}
- SFT examples: {len(sft_examples)}

## Intended Use

This dataset is designed for local post-training experiments where failed model
answers are converted into preference data and supervised examples.

## Risks

- Synthetic repairs may be directionally useful but should be reviewed before
  high-stakes training.
- Preference labels generated by the rule judge are weak labels, not a
  substitute for expert review.
"""


def render_model_card(config: dict[str, Any], eval_result: dict[str, Any]) -> str:
    return f"""# PostTrain Garden Adapter Card

Base model: `{config["base_model"]}`

Adapter output: `{config.get("output_dir")}`

## Training Method

Configured method: `{config.get("train_method")}`

LoRA enabled: `{config.get("lora", {}).get("enabled", True)}`

## Dry-run Evaluation Snapshot

```json
{json.dumps(eval_result, ensure_ascii=False, indent=2)}
```

## Limitations

This card may describe a planned adapter when only dry-run training has been
performed. Check the adapter output directory before publishing weights.
"""


def render_report(
    config: dict[str, Any],
    eval_result: dict[str, Any],
    dataset_card: Path,
    model_card: Path,
) -> str:
    counts = eval_result["counts"]
    issues = eval_result["readiness"]["issues"]
    issue_lines = "\n".join(f"- {issue}" for issue in issues) if issues else "- No readiness issues."
    return f"""# PostTrain Garden Report

Base model: `{config["base_model"]}`

## Data Loop

- Regrets: {counts["regrets"]}
- Preference pairs: {counts["preferences"]}
- SFT examples: {counts["sft_examples"]}
- Mean preference score: {eval_result["preference_score_mean"]}

## Readiness

{issue_lines}

## Artifacts

- Dataset card: `{dataset_card}`
- Model card: `{model_card}`
- Eval JSON: `{project_card_eval_path(dataset_card)}`
"""


def project_card_eval_path(dataset_card: Path) -> Path:
    return dataset_card.parent.parent / "reports" / "eval.json"
